# Generated by Django 2.2 on 2020-05-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Contact'},
        ),
        migrations.AddField(
            model_name='product',
            name='qty_available',
            field=models.FloatField(default=0.0, verbose_name='Available Stock'),
        ),
    ]
