# Generated by Django 2.2 on 2020-05-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200502_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commitment_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirm_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='filestore/product_template/', verbose_name='Image'),
        ),
    ]
