# Generated by Django 2.2 on 2020-05-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200502_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='orderlines',
            options={'verbose_name': 'Order Line'},
        ),
        migrations.RemoveField(
            model_name='orderlines',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='orderlines',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='orderlines',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderlines',
            name='untaxed_amount',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_template/', verbose_name='Image'),
        ),
    ]
