# Generated by Django 2.2 on 2020-05-03 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_customer_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Customer'),
        ),
    ]
